spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assetdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8080
